### ISSUE TITLE
Generalized beam?

### ISSUE THREAD

**Issue by smsimon** [JulienPeloton/s4cmb#14]
Is there a way to deal with beams without analytical solutions? For example, if someone provided a beam map, could this be used in the sims? If so, what format of beam map would be easy to implement?

**Comment by JulienPeloton** [comment]
For the moment there is no way to deal with beams without analytical approximations.
In order to convolve the beam response with the simulated CMB sky, one would have to rotate the grid that defines the beam geometry on a sphere for every telescope pointing defined by the scanning strategy and do the convolution... a nightmare if you have O(10k) detectors and long scans!

If someone is expert or know tricks to do that exactly and efficiently, let me know!

**Comment by JulienPeloton** [comment]
R&D problem, or million dollar problem!
