### ISSUE TITLE
Observed Pixels

### ISSUE THREAD

**Issue by smsimon** [JulienPeloton/s4cmb#17]
In scanning multiple CESs, the observed pixels are fixed from the first CES and fixed for the rest, but these may change slightly with each CES (since the array is extended).

**Comment by JulienPeloton** [comment]
Hum, I think the first part of your sentence is correct (_the observed pixels are fixed from the first CES and fixed for the rest_) but the second part is wrong (_but these may change slightly with each CES_).
Your confusion comes from a coding choice of mine. Let me explain.

1. First you are rightfully referring as to the initialisation of the output map:

```python
## Initialise map containers for each processor
if pos_CES == 0:
    sky_out_tot = OutputSkyMap(
        projection=tod.projection,
        nside=tod.nside_out,
        obspix=tod.obspix,
        npixsky=tod.npixsky,
        pixel_size=tod.pixel_size)
```

where we set `obspix=tod.obspix` when we process the first CES.

2. The obspix are defined according to the parameter `width` and the center of the patch in the initialisation of the TOD (see tod.get_obspix). It has nothing to do with your actual scanning strategy. Said differently, you will first scan an input map to produce TOD, generating an initial list of observed pixels, and then you will project your TOD on a portion of sky defined by `width`.

3. Why so? `width` defines the actual width of the sky patch you want to store in your memory, regardless the scanning strategy you defined earlier. In principle, you would like to have the full sky map stored (or just the scanned pixels - although those may change due to systematic effects). However, for high resolution maps, this demands a lot of memory and computational time (the latter because if you scan just few % of sky you would loop over a lot of pixels with value zero during mapmaking!). So I define this parameter `width` which ideally would be just slightly bigger than the intersection of all CES, to save memory and avoid looping over zeros. I completely agree though that it sounds weird, and I hope in the future I will be able to find a better way!

Here is an attempt to explain this with a picture:

![width_explained](https://user-images.githubusercontent.com/20426972/33318168-9822a880-d431-11e7-99b2-4bb217a2cfe9.jpeg)

4. What will happen if `width` does not cover all my initial observations? By default, the code will output a cropped map (see the argument `cut_pixels_outside` in the class TimeOrderedDataPairDiff). This can be useful for quick runs and debugging (where you just want to focus on a real scan strategy but get the mapmaking part done quickly). You can also force the code to crash if your `width` is too small with respect to your scans.

5. I do have infinite memory and I do not bother having a slower code, what should I do? You can set `width=360` (that is full sky output map), and you will never have any problem of cropped maps ;-)

Hope that is clear!
