### ISSUE TITLE
Index error in detector_pointing.py

### ISSUE THREAD

**Issue by joydidier** [JulienPeloton/s4cmb#19]
When running with any ini file that is not simple_parameter.py, this error comes up:

python examples/test/simple_app.py -inifile examples/inifiles/so_sac_parameters.py -tag test

Traceback (most recent call last):
  File "examples/test/simple_app.py", line 155, in <module>
    mapping_perpair=params.mapping_perpair)
  File "/data/home/joy/simons_observatory/code/s4cmb/s4cmb/tod.py", line 127, in __init__
    self.get_boresightpointing()
  File "/data/home/joy/simons_observatory/code/s4cmb/s4cmb/tod.py", line 426, in get_boresightpointing
    lat=lat, ra_src=ra_src, dec_src=dec_src)
  File "/data/home/joy/simons_observatory/code/s4cmb/s4cmb/detector_pointing.py", line 138, in __init__
    self.ut1utc = get_ut1utc(self.ut1utc_fn, self.time[0])
  File "/data/home/joy/simons_observatory/code/s4cmb/s4cmb/detector_pointing.py", line 53, in get_ut1utc
    ut1utc = ut1utcs[uindex]
IndexError: index 2193 is out of bounds for axis 0 with size 2193

**Comment by JulienPeloton** [comment]
Looking at your parameter file, you set the starting date in 2020.
However when you initialise your scanning strategy, you need to pass correction to UTC time read from ut1utc.ephem (see http://tycho.usno.navy.mil/leapsec.html on why it is necessary). This file is released with the package and contained corrections until January 1 2018, hence the error.

I will regenerate time correction for a longer period of time and let you know asap.
An alternative would be to just do a web scrapping of the data, and apply it on-the-fly (so that you do not need to read external file). But I leave that for later ;-)

**Comment by JulienPeloton** [comment]
Unfortunately the database used to compute those is currently down (http://maia.usno.navy.mil/cgi-bin/search.cgi), so until I figure out a solution, dates > 01 01 2018 will use the correction of 01 01 2018.

**Comment by JulienPeloton** [comment]
I close the issue for time being - as it is not critical for the simulations.
